// onnx.proto — muonnx runtime config + gRPC surface.
//
// Migrated from accretional/vad's onnx.proto and generalized: precision is split
// into inference vs serving; the central weight-override location is an
// ONNXWeightSource (default /onnx) instead of a bare weights_dir; host knobs live
// in ONNXEnvironmentConfig; the weight server uses a streaming Fetch; and a
// generic Inference(Tensor) service is provided for simple run-a-model use
// (cmd/eval validates the runtime through it).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: muonnx.proto

package muonnxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Precision selects an ONNX weight variant. UNSPECIFIED lets the consumer pick
// (fp32 for inference — CPU has no native fp16 kernels; fp16 for serving —
// WebGPU/transformers.js clients prefer it).
type Precision int32

const (
	Precision_PRECISION_UNSPECIFIED Precision = 0
	Precision_PRECISION_FP32        Precision = 1
	Precision_PRECISION_FP16        Precision = 2
)

// Enum value maps for Precision.
var (
	Precision_name = map[int32]string{
		0: "PRECISION_UNSPECIFIED",
		1: "PRECISION_FP32",
		2: "PRECISION_FP16",
	}
	Precision_value = map[string]int32{
		"PRECISION_UNSPECIFIED": 0,
		"PRECISION_FP32":        1,
		"PRECISION_FP16":        2,
	}
)

func (x Precision) Enum() *Precision {
	p := new(Precision)
	*p = x
	return p
}

func (x Precision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Precision) Descriptor() protoreflect.EnumDescriptor {
	return file_muonnx_proto_enumTypes[0].Descriptor()
}

func (Precision) Type() protoreflect.EnumType {
	return &file_muonnx_proto_enumTypes[0]
}

func (x Precision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Precision.Descriptor instead.
func (Precision) EnumDescriptor() ([]byte, []int) {
	return file_muonnx_proto_rawDescGZIP(), []int{0}
}

// ONNXWeightSource is where weights are provisioned at instance/container scope —
// the central dir that overrides (or is the necessary source for) per-package
// embeds. `path` defaults to /onnx when empty.
type ONNXWeightSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ONNXWeightSource) Reset() {
	*x = ONNXWeightSource{}
	mi := &file_muonnx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ONNXWeightSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ONNXWeightSource) ProtoMessage() {}

func (x *ONNXWeightSource) ProtoReflect() protoreflect.Message {
	mi := &file_muonnx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ONNXWeightSource.ProtoReflect.Descriptor instead.
func (*ONNXWeightSource) Descriptor() ([]byte, []int) {
	return file_muonnx_proto_rawDescGZIP(), []int{0}
}

func (x *ONNXWeightSource) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// ONNXModel describes one model variant in the catalog / a fetch request.
type ONNXModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uri           string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	ModelType     string                 `protobuf:"bytes,3,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Precision     Precision              `protobuf:"varint,4,opt,name=precision,proto3,enum=muonnx.Precision" json:"precision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ONNXModel) Reset() {
	*x = ONNXModel{}
	mi := &file_muonnx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ONNXModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ONNXModel) ProtoMessage() {}

func (x *ONNXModel) ProtoReflect() protoreflect.Message {
	mi := &file_muonnx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ONNXModel.ProtoReflect.Descriptor instead.
func (*ONNXModel) Descriptor() ([]byte, []int) {
	return file_muonnx_proto_rawDescGZIP(), []int{1}
}

func (x *ONNXModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ONNXModel) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ONNXModel) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ONNXModel) GetPrecision() Precision {
	if x != nil {
		return x.Precision
	}
	return Precision_PRECISION_UNSPECIFIED
}

// ONNXRuntimeConfig is the per-server runtime policy: where weights come from and
// which precision to load vs serve.
type ONNXRuntimeConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Models             []*ONNXModel           `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	WeightSource       *ONNXWeightSource      `protobuf:"bytes,2,opt,name=weight_source,json=weightSource,proto3" json:"weight_source,omitempty"`
	InferencePrecision Precision              `protobuf:"varint,3,opt,name=inference_precision,json=inferencePrecision,proto3,enum=muonnx.Precision" json:"inference_precision,omitempty"`
	ServingPrecision   Precision              `protobuf:"varint,4,opt,name=serving_precision,json=servingPrecision,proto3,enum=muonnx.Precision" json:"serving_precision,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ONNXRuntimeConfig) Reset() {
	*x = ONNXRuntimeConfig{}
	mi := &file_muonnx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ONNXRuntimeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ONNXRuntimeConfig) ProtoMessage() {}

func (x *ONNXRuntimeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_muonnx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ONNXRuntimeConfig.ProtoReflect.Descriptor instead.
func (*ONNXRuntimeConfig) Descriptor() ([]byte, []int) {
	return file_muonnx_proto_rawDescGZIP(), []int{2}
}

func (x *ONNXRuntimeConfig) GetModels() []*ONNXModel {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ONNXRuntimeConfig) GetWeightSource() *ONNXWeightSource {
	if x != nil {
		return x.WeightSource
	}
	return nil
}

func (x *ONNXRuntimeConfig) GetInferencePrecision() Precision {
	if x != nil {
		return x.InferencePrecision
	}
	return Precision_PRECISION_UNSPECIFIED
}

func (x *ONNXRuntimeConfig) GetServingPrecision() Precision {
	if x != nil {
		return x.ServingPrecision
	}
	return Precision_PRECISION_UNSPECIFIED
}

// ONNXEnvironmentConfig holds host/runtime knobs, separate from per-model policy:
// the ORT shared library (explicit; else discovered/embedded) and threading /
// execution-provider preferences.
type ONNXEnvironmentConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OnnxruntimeLib     string                 `protobuf:"bytes,1,opt,name=onnxruntime_lib,json=onnxruntimeLib,proto3" json:"onnxruntime_lib,omitempty"`
	IntraOpThreads     int32                  `protobuf:"varint,2,opt,name=intra_op_threads,json=intraOpThreads,proto3" json:"intra_op_threads,omitempty"`
	InterOpThreads     int32                  `protobuf:"varint,3,opt,name=inter_op_threads,json=interOpThreads,proto3" json:"inter_op_threads,omitempty"`
	ExecutionProviders []string               `protobuf:"bytes,4,rep,name=execution_providers,json=executionProviders,proto3" json:"execution_providers,omitempty"` // preference order, e.g. ["coreml","cpu"]
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ONNXEnvironmentConfig) Reset() {
	*x = ONNXEnvironmentConfig{}
	mi := &file_muonnx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ONNXEnvironmentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ONNXEnvironmentConfig) ProtoMessage() {}

func (x *ONNXEnvironmentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_muonnx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ONNXEnvironmentConfig.ProtoReflect.Descriptor instead.
func (*ONNXEnvironmentConfig) Descriptor() ([]byte, []int) {
	return file_muonnx_proto_rawDescGZIP(), []int{3}
}

func (x *ONNXEnvironmentConfig) GetOnnxruntimeLib() string {
	if x != nil {
		return x.OnnxruntimeLib
	}
	return ""
}

func (x *ONNXEnvironmentConfig) GetIntraOpThreads() int32 {
	if x != nil {
		return x.IntraOpThreads
	}
	return 0
}

func (x *ONNXEnvironmentConfig) GetInterOpThreads() int32 {
	if x != nil {
		return x.InterOpThreads
	}
	return 0
}

func (x *ONNXEnvironmentConfig) GetExecutionProviders() []string {
	if x != nil {
		return x.ExecutionProviders
	}
	return nil
}

type ONNXRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ONNXRequest) Reset() {
	*x = ONNXRequest{}
	mi := &file_muonnx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ONNXRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ONNXRequest) ProtoMessage() {}

func (x *ONNXRequest) ProtoReflect() protoreflect.Message {
	mi := &file_muonnx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ONNXRequest.ProtoReflect.Descriptor instead.
func (*ONNXRequest) Descriptor() ([]byte, []int) {
	return file_muonnx_proto_rawDescGZIP(), []int{4}
}

type ONNXChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ONNXChunk) Reset() {
	*x = ONNXChunk{}
	mi := &file_muonnx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ONNXChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ONNXChunk) ProtoMessage() {}

func (x *ONNXChunk) ProtoReflect() protoreflect.Message {
	mi := &file_muonnx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ONNXChunk.ProtoReflect.Descriptor instead.
func (*ONNXChunk) Descriptor() ([]byte, []int) {
	return file_muonnx_proto_rawDescGZIP(), []int{5}
}

func (x *ONNXChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// Tensor is a flat row-major float32 tensor with an explicit shape.
type Tensor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shape         []int64                `protobuf:"varint,1,rep,packed,name=shape,proto3" json:"shape,omitempty"`
	Data          []float32              `protobuf:"fixed32,2,rep,packed,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tensor) Reset() {
	*x = Tensor{}
	mi := &file_muonnx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tensor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tensor) ProtoMessage() {}

func (x *Tensor) ProtoReflect() protoreflect.Message {
	mi := &file_muonnx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tensor.ProtoReflect.Descriptor instead.
func (*Tensor) Descriptor() ([]byte, []int) {
	return file_muonnx_proto_rawDescGZIP(), []int{6}
}

func (x *Tensor) GetShape() []int64 {
	if x != nil {
		return x.Shape
	}
	return nil
}

func (x *Tensor) GetData() []float32 {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_muonnx_proto protoreflect.FileDescriptor

const file_muonnx_proto_rawDesc = "" +
	"\n" +
	"\fmuonnx.proto\x12\x06muonnx\"&\n" +
	"\x10ONNXWeightSource\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x81\x01\n" +
	"\tONNXModel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12\x1d\n" +
	"\n" +
	"model_type\x18\x03 \x01(\tR\tmodelType\x12/\n" +
	"\tprecision\x18\x04 \x01(\x0e2\x11.muonnx.PrecisionR\tprecision\"\x81\x02\n" +
	"\x11ONNXRuntimeConfig\x12)\n" +
	"\x06models\x18\x01 \x03(\v2\x11.muonnx.ONNXModelR\x06models\x12=\n" +
	"\rweight_source\x18\x02 \x01(\v2\x18.muonnx.ONNXWeightSourceR\fweightSource\x12B\n" +
	"\x13inference_precision\x18\x03 \x01(\x0e2\x11.muonnx.PrecisionR\x12inferencePrecision\x12>\n" +
	"\x11serving_precision\x18\x04 \x01(\x0e2\x11.muonnx.PrecisionR\x10servingPrecision\"\xc5\x01\n" +
	"\x15ONNXEnvironmentConfig\x12'\n" +
	"\x0fonnxruntime_lib\x18\x01 \x01(\tR\x0eonnxruntimeLib\x12(\n" +
	"\x10intra_op_threads\x18\x02 \x01(\x05R\x0eintraOpThreads\x12(\n" +
	"\x10inter_op_threads\x18\x03 \x01(\x05R\x0einterOpThreads\x12/\n" +
	"\x13execution_providers\x18\x04 \x03(\tR\x12executionProviders\"\r\n" +
	"\vONNXRequest\"%\n" +
	"\tONNXChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"2\n" +
	"\x06Tensor\x12\x14\n" +
	"\x05shape\x18\x01 \x03(\x03R\x05shape\x12\x12\n" +
	"\x04data\x18\x02 \x03(\x02R\x04data*N\n" +
	"\tPrecision\x12\x19\n" +
	"\x15PRECISION_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePRECISION_FP32\x10\x01\x12\x12\n" +
	"\x0ePRECISION_FP16\x10\x022v\n" +
	"\vONNXRuntime\x126\n" +
	"\n" +
	"ListModels\x12\x13.muonnx.ONNXRequest\x1a\x11.muonnx.ONNXModel0\x01\x12/\n" +
	"\x05Fetch\x12\x11.muonnx.ONNXModel\x1a\x11.muonnx.ONNXChunk0\x0122\n" +
	"\tInference\x12%\n" +
	"\x03Run\x12\x0e.muonnx.Tensor\x1a\x0e.muonnx.TensorB.Z,github.com/accretional/muonnx/proto/muonnxpbb\x06proto3"

var (
	file_muonnx_proto_rawDescOnce sync.Once
	file_muonnx_proto_rawDescData []byte
)

func file_muonnx_proto_rawDescGZIP() []byte {
	file_muonnx_proto_rawDescOnce.Do(func() {
		file_muonnx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_muonnx_proto_rawDesc), len(file_muonnx_proto_rawDesc)))
	})
	return file_muonnx_proto_rawDescData
}

var file_muonnx_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_muonnx_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_muonnx_proto_goTypes = []any{
	(Precision)(0),                // 0: muonnx.Precision
	(*ONNXWeightSource)(nil),      // 1: muonnx.ONNXWeightSource
	(*ONNXModel)(nil),             // 2: muonnx.ONNXModel
	(*ONNXRuntimeConfig)(nil),     // 3: muonnx.ONNXRuntimeConfig
	(*ONNXEnvironmentConfig)(nil), // 4: muonnx.ONNXEnvironmentConfig
	(*ONNXRequest)(nil),           // 5: muonnx.ONNXRequest
	(*ONNXChunk)(nil),             // 6: muonnx.ONNXChunk
	(*Tensor)(nil),                // 7: muonnx.Tensor
}
var file_muonnx_proto_depIdxs = []int32{
	0, // 0: muonnx.ONNXModel.precision:type_name -> muonnx.Precision
	2, // 1: muonnx.ONNXRuntimeConfig.models:type_name -> muonnx.ONNXModel
	1, // 2: muonnx.ONNXRuntimeConfig.weight_source:type_name -> muonnx.ONNXWeightSource
	0, // 3: muonnx.ONNXRuntimeConfig.inference_precision:type_name -> muonnx.Precision
	0, // 4: muonnx.ONNXRuntimeConfig.serving_precision:type_name -> muonnx.Precision
	5, // 5: muonnx.ONNXRuntime.ListModels:input_type -> muonnx.ONNXRequest
	2, // 6: muonnx.ONNXRuntime.Fetch:input_type -> muonnx.ONNXModel
	7, // 7: muonnx.Inference.Run:input_type -> muonnx.Tensor
	2, // 8: muonnx.ONNXRuntime.ListModels:output_type -> muonnx.ONNXModel
	6, // 9: muonnx.ONNXRuntime.Fetch:output_type -> muonnx.ONNXChunk
	7, // 10: muonnx.Inference.Run:output_type -> muonnx.Tensor
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_muonnx_proto_init() }
func file_muonnx_proto_init() {
	if File_muonnx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_muonnx_proto_rawDesc), len(file_muonnx_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_muonnx_proto_goTypes,
		DependencyIndexes: file_muonnx_proto_depIdxs,
		EnumInfos:         file_muonnx_proto_enumTypes,
		MessageInfos:      file_muonnx_proto_msgTypes,
	}.Build()
	File_muonnx_proto = out.File
	file_muonnx_proto_goTypes = nil
	file_muonnx_proto_depIdxs = nil
}
