// onnx.proto — muonnx runtime config + gRPC surface.
//
// Migrated from accretional/vad's onnx.proto and generalized: precision is split
// into inference vs serving; the central weight-override location is an
// ONNXWeightSource (default /onnx) instead of a bare weights_dir; host knobs live
// in ONNXEnvironmentConfig; the weight server uses a streaming Fetch; and a
// generic Inference(Tensor) service is provided for simple run-a-model use
// (cmd/eval validates the runtime through it).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: muonnx.proto

package muonnxpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ONNXRuntime_ListModels_FullMethodName = "/muonnx.ONNXRuntime/ListModels"
	ONNXRuntime_Fetch_FullMethodName      = "/muonnx.ONNXRuntime/Fetch"
)

// ONNXRuntimeClient is the client API for ONNXRuntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ONNXRuntime serves model weights to external clients (e.g. transformers.js on
// WebGPU). Fetch streams so it can serve any size at a requested precision.
type ONNXRuntimeClient interface {
	ListModels(ctx context.Context, in *ONNXRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ONNXModel], error)
	Fetch(ctx context.Context, in *ONNXModel, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ONNXChunk], error)
}

type oNNXRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewONNXRuntimeClient(cc grpc.ClientConnInterface) ONNXRuntimeClient {
	return &oNNXRuntimeClient{cc}
}

func (c *oNNXRuntimeClient) ListModels(ctx context.Context, in *ONNXRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ONNXModel], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ONNXRuntime_ServiceDesc.Streams[0], ONNXRuntime_ListModels_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ONNXRequest, ONNXModel]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ONNXRuntime_ListModelsClient = grpc.ServerStreamingClient[ONNXModel]

func (c *oNNXRuntimeClient) Fetch(ctx context.Context, in *ONNXModel, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ONNXChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ONNXRuntime_ServiceDesc.Streams[1], ONNXRuntime_Fetch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ONNXModel, ONNXChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ONNXRuntime_FetchClient = grpc.ServerStreamingClient[ONNXChunk]

// ONNXRuntimeServer is the server API for ONNXRuntime service.
// All implementations must embed UnimplementedONNXRuntimeServer
// for forward compatibility.
//
// ONNXRuntime serves model weights to external clients (e.g. transformers.js on
// WebGPU). Fetch streams so it can serve any size at a requested precision.
type ONNXRuntimeServer interface {
	ListModels(*ONNXRequest, grpc.ServerStreamingServer[ONNXModel]) error
	Fetch(*ONNXModel, grpc.ServerStreamingServer[ONNXChunk]) error
	mustEmbedUnimplementedONNXRuntimeServer()
}

// UnimplementedONNXRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedONNXRuntimeServer struct{}

func (UnimplementedONNXRuntimeServer) ListModels(*ONNXRequest, grpc.ServerStreamingServer[ONNXModel]) error {
	return status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedONNXRuntimeServer) Fetch(*ONNXModel, grpc.ServerStreamingServer[ONNXChunk]) error {
	return status.Error(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedONNXRuntimeServer) mustEmbedUnimplementedONNXRuntimeServer() {}
func (UnimplementedONNXRuntimeServer) testEmbeddedByValue()                     {}

// UnsafeONNXRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ONNXRuntimeServer will
// result in compilation errors.
type UnsafeONNXRuntimeServer interface {
	mustEmbedUnimplementedONNXRuntimeServer()
}

func RegisterONNXRuntimeServer(s grpc.ServiceRegistrar, srv ONNXRuntimeServer) {
	// If the following call panics, it indicates UnimplementedONNXRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ONNXRuntime_ServiceDesc, srv)
}

func _ONNXRuntime_ListModels_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ONNXRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ONNXRuntimeServer).ListModels(m, &grpc.GenericServerStream[ONNXRequest, ONNXModel]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ONNXRuntime_ListModelsServer = grpc.ServerStreamingServer[ONNXModel]

func _ONNXRuntime_Fetch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ONNXModel)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ONNXRuntimeServer).Fetch(m, &grpc.GenericServerStream[ONNXModel, ONNXChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ONNXRuntime_FetchServer = grpc.ServerStreamingServer[ONNXChunk]

// ONNXRuntime_ServiceDesc is the grpc.ServiceDesc for ONNXRuntime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ONNXRuntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "muonnx.ONNXRuntime",
	HandlerType: (*ONNXRuntimeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListModels",
			Handler:       _ONNXRuntime_ListModels_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Fetch",
			Handler:       _ONNXRuntime_Fetch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "muonnx.proto",
}

const (
	Inference_Run_FullMethodName = "/muonnx.Inference/Run"
)

// InferenceClient is the client API for Inference service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Inference runs a single model (or composite) request→response. muonnx's
// cmd/eval implements this with mult_0→add_1 to validate the runtime.
type InferenceClient interface {
	Run(ctx context.Context, in *Tensor, opts ...grpc.CallOption) (*Tensor, error)
}

type inferenceClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceClient(cc grpc.ClientConnInterface) InferenceClient {
	return &inferenceClient{cc}
}

func (c *inferenceClient) Run(ctx context.Context, in *Tensor, opts ...grpc.CallOption) (*Tensor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tensor)
	err := c.cc.Invoke(ctx, Inference_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferenceServer is the server API for Inference service.
// All implementations must embed UnimplementedInferenceServer
// for forward compatibility.
//
// Inference runs a single model (or composite) request→response. muonnx's
// cmd/eval implements this with mult_0→add_1 to validate the runtime.
type InferenceServer interface {
	Run(context.Context, *Tensor) (*Tensor, error)
	mustEmbedUnimplementedInferenceServer()
}

// UnimplementedInferenceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferenceServer struct{}

func (UnimplementedInferenceServer) Run(context.Context, *Tensor) (*Tensor, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedInferenceServer) mustEmbedUnimplementedInferenceServer() {}
func (UnimplementedInferenceServer) testEmbeddedByValue()                   {}

// UnsafeInferenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceServer will
// result in compilation errors.
type UnsafeInferenceServer interface {
	mustEmbedUnimplementedInferenceServer()
}

func RegisterInferenceServer(s grpc.ServiceRegistrar, srv InferenceServer) {
	// If the following call panics, it indicates UnimplementedInferenceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Inference_ServiceDesc, srv)
}

func _Inference_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Tensor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inference_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServer).Run(ctx, req.(*Tensor))
	}
	return interceptor(ctx, in, info, handler)
}

// Inference_ServiceDesc is the grpc.ServiceDesc for Inference service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Inference_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "muonnx.Inference",
	HandlerType: (*InferenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _Inference_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "muonnx.proto",
}
